/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/_layout'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardLayoutActiveRouteImport } from './routes/_dashboard/_layout.active'
import { Route as DashboardLayoutMatchesRouteImport } from './routes/_dashboard/_layout.matches'
import { Route as DashboardLayoutReposRouteImport } from './routes/_dashboard/_layout.repos'
import { Route as DashboardLayoutSkillsRouteImport } from './routes/_dashboard/_layout.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutActiveRoute = DashboardLayoutActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutMatchesRoute = DashboardLayoutMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutReposRoute = DashboardLayoutReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutSkillsRoute = DashboardLayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/active': typeof DashboardLayoutActiveRoute
  '/matches': typeof DashboardLayoutMatchesRoute
  '/repos': typeof DashboardLayoutReposRoute
  '/skills': typeof DashboardLayoutSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/active': typeof DashboardLayoutActiveRoute
  '/matches': typeof DashboardLayoutMatchesRoute
  '/repos': typeof DashboardLayoutReposRoute
  '/skills': typeof DashboardLayoutSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/_layout/active': typeof DashboardLayoutActiveRoute
  '/_dashboard/_layout/matches': typeof DashboardLayoutMatchesRoute
  '/_dashboard/_layout/repos': typeof DashboardLayoutReposRoute
  '/_dashboard/_layout/skills': typeof DashboardLayoutSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/auth/callback'
    | '/active'
    | '/matches'
    | '/repos'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/auth/callback'
    | '/active'
    | '/matches'
    | '/repos'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/_dashboard/_layout'
    | '/auth/callback'
    | '/_dashboard/_layout/active'
    | '/_dashboard/_layout/matches'
    | '/_dashboard/_layout/repos'
    | '/_dashboard/_layout/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_layout': {
      id: '/_dashboard/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_layout/active': {
      id: '/_dashboard/_layout/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof DashboardLayoutActiveRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/_layout/matches': {
      id: '/_dashboard/_layout/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof DashboardLayoutMatchesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/_layout/repos': {
      id: '/_dashboard/_layout/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof DashboardLayoutReposRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/_layout/skills': {
      id: '/_dashboard/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof DashboardLayoutSkillsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutActiveRoute: typeof DashboardLayoutActiveRoute
  DashboardLayoutMatchesRoute: typeof DashboardLayoutMatchesRoute
  DashboardLayoutReposRoute: typeof DashboardLayoutReposRoute
  DashboardLayoutSkillsRoute: typeof DashboardLayoutSkillsRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutActiveRoute: DashboardLayoutActiveRoute,
  DashboardLayoutMatchesRoute: DashboardLayoutMatchesRoute,
  DashboardLayoutReposRoute: DashboardLayoutReposRoute,
  DashboardLayoutSkillsRoute: DashboardLayoutSkillsRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
